main: not.savage.motd.bukkit.BukkitMOTDPlugin
version: 1.0.0-DEV
name: ShockMOTD
author: Savage
description: Simple, Lightweight MOTD plugin for Paper & Velocity.
depend: [ SVCommonsLib, ProtocolLib ]